kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: app-name-runtime
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'app-name-runtime:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'open-liberty:kernel-slim-java11-openj9-ubi'
  postCommit: {}
  source:
    type: Dockerfile
    dockerfile: |-
      FROM open-liberty:kernel-slim-java11-openj9-ubi
      COPY --chown=1001:0 src/src/main/liberty/config /config
      RUN features.sh
      COPY --chown=1001:0 src/target/*.war /config/apps
      RUN configure.sh
    images:
      - from:
          kind: ImageStreamTag
          name: 'app-name:latest'
        paths:
          - sourcePath: /tmp/src
            destinationDir: .
  triggers:
    - type: ImageChange
      imageChange: {}
    - type: ImageChange
      imageChange:
        from:
          kind: ImageStreamTag
          name: 'app-name:latest'
  runPolicy: Serial
